// Mock API service — returns realistic dummy data for all views

export const mockCases = [
  {
    id: 'CASE-001',
    cropType: 'Paddy (Rice)',
    variety: 'Samba',
    location: 'Ampara, Eastern Province',
    disease: 'Blast Disease',
    scientificName: 'Magnaporthe oryzae',
    confidence: 94,
    severity: 'high',
    status: 'confirmed',
    spreadRisk: 78,
    submittedAt: '2026-09-11T10:30:00Z',
    updatedAt: '2026-09-11T14:20:00Z',
    farmerId: 1,
    farmerName: 'Ruwan Perera',
    officerId: 2,
    imageUrl: null,
    symptoms: 'Diamond-shaped lesions with gray centers on leaves, brownish margins, neck rot visible',
    weatherContext: { humidity: 87, temp: 28, rainfall: 12 },
    nearbyAlerts: 3,
    treatmentSteps: [
      'Remove and destroy severely infected plant parts immediately',
      'Apply Tricyclazole (Beam) @ 0.6g/L or Isoprothiolane (Fuji-One) @ 1.5ml/L',
      'Ensure proper field drainage to reduce humidity',
      'Avoid excessive nitrogen application',
      'Monitor neighboring fields and alert farmers within 2km radius',
    ],
    affectedArea: '0.8 acres',
    estimatedLoss: '35%',
  },
  {
    id: 'CASE-002',
    cropType: 'Tea',
    variety: 'TRI-2043',
    location: 'Nuwara Eliya, Central Province',
    disease: 'Blister Blight',
    scientificName: 'Exobasidium vexans',
    confidence: 89,
    severity: 'medium',
    status: 'escalated',
    spreadRisk: 62,
    submittedAt: '2026-09-10T08:15:00Z',
    updatedAt: '2026-09-10T16:45:00Z',
    farmerId: 1,
    farmerName: 'Ruwan Perera',
    officerId: null,
    imageUrl: null,
    symptoms: 'Pale green translucent spots on young leaves, white powdery growth on underside',
    weatherContext: { humidity: 92, temp: 18, rainfall: 28 },
    nearbyAlerts: 7,
    treatmentSteps: [
      'Apply copper-based fungicides (Copper oxychloride) at 2.5g/L',
      'Improve air circulation by proper pruning',
      'Avoid working in wet conditions to prevent spread',
      'Apply systemic fungicide Hexaconazole @ 2ml/10L',
    ],
    affectedArea: '1.2 acres',
    estimatedLoss: '20%',
  },
  {
    id: 'CASE-003',
    cropType: 'Maize (Corn)',
    variety: 'NK-6240',
    location: 'Kurunegala, North Western Province',
    disease: 'Fall Armyworm',
    scientificName: 'Spodoptera frugiperda',
    confidence: 97,
    severity: 'critical',
    status: 'pending',
    spreadRisk: 91,
    submittedAt: '2026-09-11T06:00:00Z',
    updatedAt: '2026-09-11T06:00:00Z',
    farmerId: 1,
    farmerName: 'Chamara Bandara',
    officerId: null,
    imageUrl: null,
    symptoms: 'Ragged holes in leaves, frass in whorls, irregular window feeding on leaves',
    weatherContext: { humidity: 75, temp: 32, rainfall: 0 },
    nearbyAlerts: 12,
    treatmentSteps: [
      'Apply Emamectin benzoate (Proclaim) @ 0.4g/L immediately',
      'Use Spinetoram (Delegate) @ 0.5ml/L for effective control',
      'Set up pheromone traps (5 per acre) for monitoring',
      'Alert neighboring maize farmers within 5km radius',
      'Conduct scouting every 3 days',
    ],
    affectedArea: '3.5 acres',
    estimatedLoss: '60%',
  },
  {
    id: 'CASE-004',
    cropType: 'Coconut',
    variety: 'Sri Lanka Tall',
    location: 'Puttalam, North Western Province',
    disease: 'Weligama Coconut Leaf Wilt',
    scientificName: 'Phytoplasma sp.',
    confidence: 72,
    severity: 'high',
    status: 'escalated',
    spreadRisk: 85,
    submittedAt: '2026-09-09T11:00:00Z',
    updatedAt: '2026-09-10T09:30:00Z',
    farmerId: 5,
    farmerName: 'Priya Jayawardena',
    officerId: 2,
    imageUrl: null,
    symptoms: 'Yellowing of lower fronds, premature nut fall, reduction in inflorescences',
    weatherContext: { humidity: 80, temp: 30, rainfall: 5 },
    nearbyAlerts: 5,
    treatmentSteps: [
      'Remove and burn all infected palms immediately',
      'Apply oxytetracycline injections to early-stage infected palms',
      'Control insect vectors (leafhopper) using insecticides',
      'Quarantine the affected area',
      'Report to Coconut Cultivation Board immediately',
    ],
    affectedArea: '5 acres',
    estimatedLoss: '45%',
  },
  {
    id: 'CASE-005',
    cropType: 'Tomato',
    variety: 'T-245',
    location: 'Badulla, Uva Province',
    disease: 'Late Blight',
    scientificName: 'Phytophthora infestans',
    confidence: 91,
    severity: 'high',
    status: 'treated',
    spreadRisk: 45,
    submittedAt: '2026-09-08T14:00:00Z',
    updatedAt: '2026-09-09T10:00:00Z',
    farmerId: 1,
    farmerName: 'Ruwan Perera',
    officerId: 2,
    imageUrl: null,
    symptoms: 'Water-soaked lesions on leaves, white mold on undersides, brown stem lesions',
    weatherContext: { humidity: 90, temp: 22, rainfall: 18 },
    nearbyAlerts: 2,
    treatmentSteps: [
      'Apply Metalaxyl + Mancozeb (Ridomil Gold) @ 2.5g/L',
      'Remove affected plant material and dispose properly',
      'Improve drainage and reduce leaf wetness',
      'Apply preventive copper sprays every 7 days',
    ],
    affectedArea: '0.5 acres',
    estimatedLoss: '25%',
  },
];

export const mockOutbreaks = [
  { id: 1, disease: 'Fall Armyworm', crop: 'Maize', region: 'North Western', activeCases: 47, trend: 'rising', severity: 'critical', lastUpdated: '2026-09-11' },
  { id: 2, disease: 'Blast Disease', crop: 'Paddy', region: 'Eastern', activeCases: 31, trend: 'stable', severity: 'high', lastUpdated: '2026-09-11' },
  { id: 3, disease: 'Blister Blight', crop: 'Tea', region: 'Central', activeCases: 19, trend: 'falling', severity: 'medium', lastUpdated: '2026-09-10' },
  { id: 4, disease: 'Leaf Curl Virus', crop: 'Chilli', region: 'Uva', activeCases: 12, trend: 'rising', severity: 'medium', lastUpdated: '2026-09-10' },
  { id: 5, disease: 'Weligama Leaf Wilt', crop: 'Coconut', region: 'North Western', activeCases: 8, trend: 'stable', severity: 'high', lastUpdated: '2026-09-09' },
];

export const mockStats = {
  farmer: {
    totalCases: 12,
    activeCases: 3,
    treatedCases: 8,
    escalatedCases: 1,
    cropsSaved: '78%',
    lastDiagnosis: 'Blast Disease',
  },
  officer: {
    pendingReview: 8,
    fieldVisitsToday: 2,
    confirmedThisWeek: 15,
    escalatedCases: 4,
    avgResponseTime: '2.4 hrs',
    accuracy: '96%',
  },
  research: {
    activeOutbreaks: 5,
    diseasesTracked: 23,
    regionsMonitored: 9,
    alertsSent: 47,
    modelsDeployed: 3,
    dataPoints: '14.2K',
  },
  admin: {
    totalUsers: 1243,
    activeOfficers: 28,
    casesToday: 34,
    alertsSent: 12,
    systemUptime: '99.8%',
    pendingApprovals: 6,
  },
};

export const mockWeather = {
  current: { temp: 28, humidity: 82, rainfall: 8, windSpeed: 12, condition: 'Partly Cloudy' },
  forecast: [
    { day: 'Mon', temp: 29, rainfall: 5, riskLevel: 'low' },
    { day: 'Tue', temp: 27, rainfall: 18, riskLevel: 'high' },
    { day: 'Wed', temp: 26, rainfall: 22, riskLevel: 'high' },
    { day: 'Thu', temp: 28, rainfall: 10, riskLevel: 'medium' },
    { day: 'Fri', temp: 30, rainfall: 2, riskLevel: 'low' },
  ],
};

export const mockOfficers = [
  { id: 1, name: 'Nimali Fernando', district: 'Kandy', activeCases: 8, phone: '+94 71 987 6543', status: 'active' },
  { id: 2, name: 'Pradeep Rathnayake', district: 'Kurunegala', activeCases: 12, phone: '+94 77 456 7890', status: 'active' },
  { id: 3, name: 'Sanduni Wickrama', district: 'Ampara', activeCases: 6, phone: '+94 71 234 5678', status: 'active' },
  { id: 4, name: 'Hasantha Gunasekara', district: 'Nuwara Eliya', activeCases: 4, phone: '+94 76 789 0123', status: 'field' },
];

export const mockUsers = [
  { id: 1, name: 'Ruwan Perera', email: 'ruwan@farm.lk', role: 'farmer', status: 'active', joinedAt: '2026-01-15', cases: 12 },
  { id: 2, name: 'Chamara Bandara', email: 'chamara@farm.lk', role: 'farmer', status: 'active', joinedAt: '2026-02-20', cases: 5 },
  { id: 3, name: 'Priya Jayawardena', email: 'priya@farm.lk', role: 'farmer', status: 'active', joinedAt: '2026-03-10', cases: 8 },
  { id: 4, name: 'Nimali Fernando', email: 'nimali@agri.gov.lk', role: 'officer', status: 'active', joinedAt: '2026-01-05', cases: 47 },
  { id: 5, name: 'Dr. Kasun Silva', email: 'kasun@research.lk', role: 'research', status: 'active', joinedAt: '2026-01-01', cases: 0 },
  { id: 6, name: 'Anura Dissanayake', email: 'anura@farm.lk', role: 'farmer', status: 'inactive', joinedAt: '2026-04-01', cases: 2 },
];

export const mockFieldVisits = [
  { id: 1, farmerId: 1, farmerName: 'Ruwan Perera', caseId: 'CASE-001', location: 'Ampara', crop: 'Paddy', scheduledDate: '2026-09-12', status: 'scheduled', priority: 'high' },
  { id: 2, farmerId: 5, farmerName: 'Priya Jayawardena', caseId: 'CASE-004', location: 'Puttalam', crop: 'Coconut', scheduledDate: '2026-09-13', status: 'scheduled', priority: 'high' },
  { id: 3, farmerId: 2, farmerName: 'Chamara Bandara', caseId: 'CASE-003', location: 'Kurunegala', crop: 'Maize', scheduledDate: '2026-09-11', status: 'completed', priority: 'critical' },
  { id: 4, farmerId: 3, farmerName: 'Nihal Gunasekara', caseId: 'CASE-006', location: 'Kandy', crop: 'Tea', scheduledDate: '2026-09-14', status: 'scheduled', priority: 'medium' },
];

export const mockVisits = [
  { id: 'VISIT-001', farmerId: 1, farmerName: 'Ruwan Perera', caseId: 'CASE-001', location: 'Ampara, Eastern Province', cropType: 'Paddy (Rice)', scheduledDate: '2026-09-14', status: 'scheduled', priority: 'high', notes: 'Verify Blast Disease spore density and supply bio-control recommendations.' },
  { id: 'VISIT-002', farmerId: 2, farmerName: 'Chamara Bandara', caseId: 'CASE-003', location: 'Kurunegala, NW Province', cropType: 'Maize', scheduledDate: '2026-09-13', status: 'completed', priority: 'critical', notes: 'Fall armyworm pheromone traps deployed successfully.' },
  { id: 'VISIT-003', farmerId: 5, farmerName: 'Priya Jayawardena', caseId: 'CASE-004', location: 'Puttalam, NW Province', cropType: 'Coconut', scheduledDate: '2026-09-15', status: 'scheduled', priority: 'high', notes: 'Assess Weligama leaf wilt symptom spread.' },
  { id: 'VISIT-004', farmerId: 3, farmerName: 'Nihal Gunasekara', caseId: 'CASE-006', location: 'Kandy, Central Province', cropType: 'Tea', scheduledDate: '2026-09-16', status: 'scheduled', priority: 'medium', notes: 'Routine check of foliage fungicide spray coverage.' },
];

export const api = {
  getCases: () => Promise.resolve(mockCases),
  getCaseById: (id) => Promise.resolve(mockCases.find(c => c.id === id) || mockCases[0]),
  getStats: (role) => Promise.resolve(mockStats[role] || mockStats.farmer),
  getOutbreaks: () => Promise.resolve(mockOutbreaks),
  getWeather: () => Promise.resolve(mockWeather),
  getOfficers: () => Promise.resolve(mockOfficers),
  getUsers: () => Promise.resolve(mockUsers),
  getFieldVisits: () => Promise.resolve(mockFieldVisits),
  submitCase: (data) => Promise.resolve({ id: 'CASE-' + Math.floor(Math.random() * 1000), ...data }),
  updateCaseStatus: (id, status) => Promise.resolve({ id, status }),
};

export default api;
