-- AgroGuard-AI PostgreSQL Seed Data (for Supabase PostgreSQL)
-- BCrypt Hash for 'password123': $2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O

-- 1. SEED USERS
INSERT INTO users (id, name, email, password_hash, role, avatar, phone, location, status, district, badge_id, farm_size, institution, specialization, permissions) VALUES
(1, 'Ruwan Perera', 'ruwan@farm.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'farmer', 'RP', '+94 77 123 4567', 'Ampara, Eastern Province', 'active', 'Ampara', NULL, '2.4 acres', NULL, NULL, '[]'::jsonb),
(2, 'Dr. Anura Bandara', 'anura@agridept.gov.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'officer', 'AB', '+94 71 987 6543', 'Batticaloa & Ampara', 'active', 'Eastern Division', 'AGO-2024-045', NULL, 'Department of Agriculture', 'Crop Protection', '[]'::jsonb),
(3, 'Prof. Dhammika Silva', 'dhammika@cri.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'research', 'DS', '+94 76 345 6789', 'Peradeniya CRI', 'active', 'Central Division', 'RES-2024-012', NULL, 'Crop Research Institute', 'Plant Pathology & Epidemiology', '[]'::jsonb),
(4, 'System Administrator', 'admin@agroguard.gov.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'admin', 'SA', '+94 11 234 5678', 'Central Operations, Colombo', 'active', 'National HQ', 'ADM-001', NULL, 'Ministry of Agriculture', 'System Control', '["all"]'::jsonb),
(5, 'Chamara Bandara', 'chamara@farm.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'farmer', 'CB', '+94 77 234 5678', 'Kurunegala, North Western Province', 'active', 'Kurunegala', NULL, '3.5 acres', NULL, NULL, '[]'::jsonb),
(6, 'Priya Jayawardena', 'priya@farm.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'farmer', 'PJ', '+94 77 345 6789', 'Puttalam, North Western Province', 'active', 'Puttalam', NULL, '5.0 acres', NULL, NULL, '[]'::jsonb),
(7, 'Nimali Fernando', 'nimali@agri.gov.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'officer', 'NF', '+94 71 234 5678', 'Kandy District', 'active', 'Central Division', 'AGO-2024-089', NULL, 'Department of Agriculture', 'Extension Services', '[]'::jsonb),
(10, 'Sunil Jayasuriya', 'sunil@farm.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'farmer', 'SJ', '+94 77 456 7890', 'Ampara East, Eastern Province', 'active', 'Ampara', NULL, '3.0 acres', NULL, NULL, '[]'::jsonb),
(11, 'Kithsiri Gamage', 'kithsiri@farm.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'farmer', 'KG', '+94 77 567 8901', 'Digamadulla, Eastern Province', 'active', 'Ampara', NULL, '4.2 acres', NULL, NULL, '[]'::jsonb),
(12, 'Aruna Kumara', 'aruna@farm.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'farmer', 'AK', '+94 77 678 9012', 'Uhana, Eastern Province', 'active', 'Ampara', NULL, '2.8 acres', NULL, NULL, '[]'::jsonb),
(13, 'Mahinda Rathnayake', 'mahinda@farm.lk', '$2a$10$3euPcmQFCiblsZeEu5s7p.9V8KjJdZ0u5Jm3n9P0yIiqv8I2E8s5O', 'farmer', 'MR', '+94 77 789 0123', 'Polonnaruwa, North Central Province', 'active', 'Polonnaruwa', NULL, '6.0 acres', NULL, NULL, '[]'::jsonb)
ON CONFLICT (email) DO NOTHING;

-- 2. SEED FARMS
INSERT INTO farms (id, farmer_id, farm_name, crop, variety, latitude, longitude, district, province, area) VALUES
(1, 1, 'Jayabima Paddy Holding', 'Paddy (Rice)', 'Samba / Bg 352', 7.2912, 81.6724, 'Ampara', 'Eastern Province', '2.4 acres'),
(2, 1, 'Samanala Tea Plot', 'Tea', 'TRI-2043', 6.9497, 80.7891, 'Nuwara Eliya', 'Central Province', '1.5 acres'),
(3, 5, 'Wayamba Maize Fields', 'Maize (Corn)', 'NK-6240', 7.4863, 80.3623, 'Kurunegala', 'North Western Province', '3.5 acres'),
(4, 6, 'Puttalam Palm Estate', 'Coconut', 'Sri Lanka Tall', 8.0362, 79.8283, 'Puttalam', 'North Western Province', '5.0 acres'),
(5, 1, 'Uva Green Tomato Farm', 'Tomato', 'Thilina', 6.9934, 81.0550, 'Badulla', 'Uva Province', '0.5 acres'),
(6, 10, 'Ampara East Paddy Field', 'Paddy (Rice)', 'Bg 358', 7.3050, 81.6810, 'Ampara', 'Eastern Province', '3.0 acres'),
(7, 11, 'Digamadulla Holdings', 'Paddy (Rice)', 'At 362', 7.3200, 81.6950, 'Ampara', 'Eastern Province', '4.2 acres'),
(8, 12, 'Uhana Rice Project', 'Paddy (Rice)', 'Bw 367', 7.3600, 81.6500, 'Ampara', 'Eastern Province', '2.8 acres'),
(9, 13, 'Polonnaruwa Harvest Farm', 'Paddy (Rice)', 'Keeri Samba', 7.9403, 81.0188, 'Polonnaruwa', 'North Central Province', '6.0 acres')
ON CONFLICT (id) DO NOTHING;

-- 3. SEED CASES
INSERT INTO cases (id, farmer_id, farm_id, farmer_name, crop_type, variety, location, latitude, longitude, field_area, crop_stage, symptoms, image_url, disease, scientific_name, confidence, severity, status, spread_risk, language, weather_context, nearby_alerts, treatment_steps, prevention_steps, affected_area, estimated_loss, officer_id, officer_notes, escalation_reason, officer_verified, verified_disease, verified_severity, verified_at, verified_by, created_at, updated_at) VALUES
('CASE-001', 1, 1, 'Ruwan Perera', 'Paddy (Rice)', 'Samba', 'Ampara, Eastern Province', 7.2912, 81.6724, '1.2 acres', 'Tillering / Vegetative', 'Diamond-shaped lesions with gray centers on leaves, brownish margins, neck rot visible', 'https://images.unsplash.com/photo-1530507629858-e4977d30e9e0?w=800', 'Blast Disease', 'Magnaporthe oryzae', 94, 'high', 'confirmed', 78, 'en', '{"humidity": 87, "temp": 28, "rainfall": 12}'::jsonb, 3, '["Remove and destroy severely infected plant parts immediately", "Apply Tricyclazole (Beam) @ 0.6g/L or Isoprothiolane (Fuji-One) @ 1.5ml/L", "Ensure proper field drainage to reduce humidity", "Avoid excessive nitrogen application", "Monitor neighboring fields and alert farmers within 2km radius"]'::jsonb, '["Plant certified resistant cultivars (Bg 358, Bg 379/2)", "Maintain balanced fertilization with split potassium doses", "Avoid late-season planting when morning dew duration exceeds 8 hours"]'::jsonb, '0.8 acres', '35%', 2, 'Field symptoms match typical blast lesions. Spore count accelerated by recent morning dew. Approved application of systemic fungicide.', NULL, true, 'Blast Disease', 'high', NOW() - INTERVAL '4 hours', 2, NOW() - INTERVAL '1 day', NOW() - INTERVAL '4 hours'),
('CASE-002', 1, 2, 'Ruwan Perera', 'Tea', 'TRI-2043', 'Nuwara Eliya, Central Province', 6.9497, 80.7891, '1.5 acres', 'Flushing', 'Pale green translucent spots on young leaves, white powdery growth on underside', 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800', 'Blister Blight', 'Exobasidium vexans', 89, 'medium', 'escalated', 62, 'en', '{"humidity": 92, "temp": 18, "rainfall": 28}'::jsonb, 1, '["Apply copper-based fungicides (Copper oxychloride) at 2.5g/L", "Improve air circulation by proper pruning", "Avoid working in wet conditions to prevent spread", "Apply systemic fungicide Hexaconazole @ 2ml/10L"]'::jsonb, '["Regulate shade trees to allow morning sun penetration", "Prune bushes on correct schedule", "Harvest tender flush systematically"]'::jsonb, '1.2 acres', '20%', NULL, NULL, 'Unusually fast spread on tender flush leaves despite initial copper oxychloride spray. Need field inspection.', false, NULL, NULL, NULL, NULL, NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day'),
('CASE-003', 5, 3, 'Chamara Bandara', 'Maize (Corn)', 'NK-6240', 'Kurunegala, North Western Province', 7.4863, 80.3623, '3.5 acres', 'Whorl Stage', 'Ragged holes in leaves, frass in whorls, irregular window feeding on leaves', 'https://images.unsplash.com/photo-1551893478-d726eaf0442c?w=800', 'Fall Armyworm', 'Spodoptera frugiperda', 97, 'critical', 'pending', 91, 'en', '{"humidity": 75, "temp": 32, "rainfall": 0}'::jsonb, 4, '["Apply Emamectin benzoate (Proclaim) @ 0.4g/L immediately into whorls", "Use Spinetoram (Delegate) @ 0.5ml/L for effective second-generation control", "Set up pheromone traps (5 per acre) for continuous monitoring", "Alert neighboring maize farmers within 5km radius", "Conduct scouting every 3 days"]'::jsonb, '["Synchronized planting across adjacent blocks", "Intercrop with non-host pulses", "Handpick egg masses and young larvae during early whorl stage"]'::jsonb, '3.5 acres', '60%', NULL, NULL, 'Critical pest severity detected automatically by AI.', false, NULL, NULL, NULL, NULL, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '6 hours'),
('CASE-004', 6, 4, 'Priya Jayawardena', 'Coconut', 'Sri Lanka Tall', 'Puttalam, North Western Province', 8.0362, 79.8283, '5.0 acres', 'Bearing', 'Yellowing of lower fronds, premature nut fall, reduction in inflorescences', 'https://images.unsplash.com/photo-1598880940371-c756e015fea1?w=800', 'Weligama Coconut Leaf Wilt', 'Phytoplasma sp.', 71, 'high', 'escalated', 85, 'en', '{"humidity": 80, "temp": 30, "rainfall": 5}'::jsonb, 2, '["Remove and burn all infected palms immediately", "Apply oxytetracycline injections to early-stage infected palms", "Control insect vectors (leafhopper) using insecticides", "Quarantine the affected area", "Report to Coconut Cultivation Board immediately"]'::jsonb, '["Plant vector-tolerant coconut varieties", "Regular weed sanitation to suppress vector habitats", "Strict quarantine on transport of planting material"]'::jsonb, '5 acres', '45%', 2, NULL, 'Low AI confidence (71%) on leaf wilt. Automatically escalated for field officer validation.', false, NULL, NULL, NULL, NULL, NOW() - INTERVAL '3 days', NOW() - INTERVAL '2 days'),
('CASE-005', 1, 5, 'Ruwan Perera', 'Tomato', 'Thilina', 'Badulla, Uva Province', 6.9934, 81.0550, '0.5 acres', 'Flowering & Fruiting', 'Water-soaked lesions on leaves, white mold on undersides, brown stem lesions', 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=800', 'Late Blight', 'Phytophthora infestans', 91, 'high', 'treated', 45, 'en', '{"humidity": 90, "temp": 22, "rainfall": 18}'::jsonb, 1, '["Apply Metalaxyl + Mancozeb (Ridomil Gold) @ 2.5g/L", "Remove affected plant material and dispose properly", "Improve drainage and reduce leaf wetness", "Apply preventive copper sprays every 7 days"]'::jsonb, '["Avoid overhead irrigation", "Stake plants and mulch soil", "Rotate with non-solanaceous crops"]'::jsonb, '0.5 acres', '25%', 2, 'Farmer completed spray protocol on Sep 9. Spot necrosis arrested.', NULL, true, 'Late Blight', 'high', NOW() - INTERVAL '3 days', 2, NOW() - INTERVAL '4 days', NOW() - INTERVAL '3 days'),
('CASE-006', 10, 6, 'Sunil Jayasuriya', 'Paddy (Rice)', 'Bg 358', 'Ampara East, Eastern Province', 7.3050, 81.6810, '3.0 acres', 'Tillering', 'Spindle-shaped brown lesions with gray centers spreading rapidly across leaf blades', 'https://images.unsplash.com/photo-1530507629858-e4977d30e9e0?w=800', 'Blast Disease', 'Magnaporthe oryzae', 92, 'high', 'confirmed', 82, 'en', '{"humidity": 88, "temp": 28, "rainfall": 15}'::jsonb, 3, '["Apply Tricyclazole @ 0.6g/L immediately", "Drain stagnant water from paddy bunds", "Suspend nitrogen top dressing"]'::jsonb, '["Plant resistant varieties", "Maintain wide spacing for air ventilation"]'::jsonb, '1.5 acres', '30%', 2, 'Matches neighboring CASE-001 spore propagation pattern. Confirmed.', NULL, true, 'Blast Disease', 'high', NOW() - INTERVAL '12 hours', 2, NOW() - INTERVAL '18 hours', NOW() - INTERVAL '12 hours'),
('CASE-007', 11, 7, 'Kithsiri Gamage', 'Paddy (Rice)', 'At 362', 'Digamadulla, Eastern Province', 7.3200, 81.6950, '4.2 acres', 'Panicle Initiation', 'Brownish necrotic lesions on flag leaves, neck blast symptoms emerging', 'https://images.unsplash.com/photo-1530507629858-e4977d30e9e0?w=800', 'Blast Disease', 'Magnaporthe oryzae', 95, 'critical', 'confirmed', 88, 'en', '{"humidity": 89, "temp": 27, "rainfall": 18}'::jsonb, 3, '["Urgent application of Isoprothiolane @ 1.5ml/L", "Create buffer isolation strip around affected blocks", "Alert regional extension center"]'::jsonb, '["Treat seeds with carbendazim prior to sowing", "Avoid late season nitrogen application"]'::jsonb, '2.0 acres', '45%', 2, 'Third confirmed blast case in 5km corridor. Urgent outbreak response triggered.', NULL, true, 'Blast Disease', 'critical', NOW() - INTERVAL '5 hours', 2, NOW() - INTERVAL '8 hours', NOW() - INTERVAL '5 hours')
ON CONFLICT (id) DO NOTHING;

-- 4. SEED FIELD VISITS
INSERT INTO field_visits (id, case_id, farmer_id, officer_id, farmer_name, location, crop_type, scheduled_date, status, priority, notes, observed_symptoms, confirmed_disease, verified_severity, recommendation, completed_at) VALUES
('VISIT-001', 'CASE-001', 1, 2, 'Ruwan Perera', 'Ampara, Eastern Province', 'Paddy (Rice)', CURRENT_DATE + INTERVAL '2 days', 'scheduled', 'high', 'Verify Blast Disease spore density and supply bio-control recommendations.', NULL, NULL, NULL, NULL, NULL),
('VISIT-002', 'CASE-003', 5, 2, 'Chamara Bandara', 'Kurunegala, NW Province', 'Maize', CURRENT_DATE - INTERVAL '1 day', 'completed', 'critical', 'Fall armyworm pheromone traps deployed successfully.', 'Larval frass in 40% of whorls inspected. First instar larvae confirmed.', 'Fall Armyworm', 'critical', 'Deploy synchronized Emamectin benzoate application across 3 adjacent farms.', NOW() - INTERVAL '1 day'),
('VISIT-003', 'CASE-004', 6, 2, 'Priya Jayawardena', 'Puttalam, NW Province', 'Coconut', CURRENT_DATE + INTERVAL '3 days', 'scheduled', 'high', 'Assess Weligama leaf wilt symptom spread and vector management protocol.', NULL, NULL, NULL, NULL, NULL),
('VISIT-004', 'CASE-007', 11, 2, 'Kithsiri Gamage', 'Digamadulla, Eastern Province', 'Paddy (Rice)', CURRENT_DATE - INTERVAL '3 hours', 'completed', 'critical', 'Emergency cluster verification for Ampara Rice Belt.', 'Neck blast sporulation visible on 30% of hills. Severe leaf necrosis.', 'Blast Disease', 'critical', 'Quarantine block 3, initiate aerial spray buffer, alert all farms within 10km.', NOW() - INTERVAL '3 hours')
ON CONFLICT (id) DO NOTHING;

-- 5. SEED OUTBREAKS
INSERT INTO outbreaks (id, disease, crop, region, district, center_lat, center_lng, radius_km, active_cases, affected_farms, trend, severity, status, confirmed_by, confirmed_at, last_updated) VALUES
(1, 'Blast Disease', 'Paddy (Rice)', 'Eastern Province', 'Ampara', 7.3054, 81.6828, 10.0, 3, 4, 'rising', 'critical', 'confirmed', 4, NOW() - INTERVAL '2 hours', CURRENT_DATE),
(2, 'Fall Armyworm', 'Maize (Corn)', 'North Western Province', 'Kurunegala', 7.4863, 80.3623, 15.0, 1, 1, 'rising', 'high', 'potential', NULL, NULL, CURRENT_DATE),
(3, 'Blister Blight', 'Tea', 'Central Province', 'Nuwara Eliya', 6.9497, 80.7891, 8.0, 1, 1, 'stable', 'medium', 'potential', NULL, NULL, CURRENT_DATE - INTERVAL '1 day')
ON CONFLICT (id) DO NOTHING;

-- 6. SEED ALERTS
INSERT INTO alerts (id, province, threat_level, crop_target, message, created_by, created_at) VALUES
(1, 'Eastern Province', 'Critical', 'Paddy (Rice)', 'Confirmed Blast Disease Outbreak Cluster in Ampara Agrarian Division. 3 active confirmed foci within 4.2 km. Neighboring farms within 10 km must apply preventive fungicide immediately.', 4, NOW() - INTERVAL '2 hours'),
(2, 'North Western Province', 'High', 'Maize', 'Fall Armyworm active watch triggered across Kurunegala and Puttalam. Inspect maize whorls immediately.', 4, NOW() - INTERVAL '1 day')
ON CONFLICT (id) DO NOTHING;

-- 7. SEED NOTIFICATIONS
INSERT INTO notifications (id, user_id, text, type, is_read, link, created_at) VALUES
(1, 1, 'URGENT: Blast Disease outbreak confirmed within 2.1 km of your farm Jayabima Holding. Inspect bunds immediately.', 'alert', false, '/farmer/cases', NOW() - INTERVAL '2 hours'),
(2, 10, 'URGENT: Blast Disease outbreak confirmed in your area. Neighboring farm flagged.', 'alert', false, '/farmer/cases', NOW() - INTERVAL '2 hours'),
(3, 1, 'Your case CASE-001 has been verified on-site by Dr. Anura Bandara. Treatment confirmed.', 'success', false, '/farmer/diagnosis/CASE-001', NOW() - INTERVAL '4 hours'),
(4, 2, 'CASE-004 escalated to you: Low confidence AI diagnosis requires field verification in Puttalam.', 'alert', false, '/officer/case/CASE-004', NOW() - INTERVAL '2 days'),
(5, 11, 'Field inspection completed for CASE-007 by Dr. Anura Bandara. Case marked confirmed.', 'success', true, '/farmer/diagnosis/CASE-007', NOW() - INTERVAL '3 hours')
ON CONFLICT (id) DO NOTHING;

